spring:
  config:
    import: optional:classpath:codex-runtime-defaults.yml
  ai:
    mcp:
      server:
        name: mcp-weather-server
        protocol: STREAMABLE
        request-timeout: 1h
        port: 8080
